### ISSUE TITLE
报错panic: lookup api.lib.cn: no such host

### ISSUE THREAD

**Issue by ShakeM** [vikadata/vika.go#5]
datasheet := vika.New(vika.VikaConfig{Token: appToken}).Datasheet(tableToken)

	res, err := datasheet.Upload("upload.xlsx")
	if err != nil {
		panic(err)
	}

报错panic: lookup api.lib.cn: no such host

**Comment by ShakeM** [comment]
已变相解决，在VikaConfig中手动使用“https://api.vika.cn”作为Host.

**Comment by zoe-icu** [comment]
@ShakeM 你是用的v0.0.1版本么？ 我测试了v0.0.1版本现在没有这个问题，你重新更新包试试呢？
github.com/vikadata/vika.go v0.0.1

**Comment by ShakeM** [comment]
> @ShakeM 你是用的v0.0.1版本么？ 我测试了v0.0.1版本现在没有这个问题，你重新更新包试试呢？
> go get github.com/vikadata/vika.go@v0.0.1

使用的是go get github.com/vikadata/vika.go

**Comment by ShakeM** [comment]
> @ShakeM 你是用的v0.0.1版本么？ 我测试了v0.0.1版本现在没有这个问题，你重新更新包试试呢？
> go get github.com/vikadata/vika.go@v0.0.1

已变相解决，在VikaConfig中手动使用“https://api.vika.cn”作为Host.

**Comment by OUCHUNYU** [comment]
🚀🚀
